# Generated by Django 4.1.4 on 2023-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elevatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(max_length=200)),
                ('restingFloor', models.CharField(max_length=200)),
                ('vacancy', models.BooleanField(default=True)),
                ('NumberofFloors', models.PositiveIntegerField()),
            ],
        ),
    ]
