# Generated by Django 4.1.4 on 2023-02-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatormodel',
            name='NumberofFloors',
        ),
    ]
