# Generated by Django 4.1.6 on 2023-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_remove_elevatormodel_numberoffloors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatormodel',
            name='restingFloor',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
