# Generated by Django 4.1.6 on 2023-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_alter_elevatormodel_restingfloor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatormodel',
            name='moving',
            field=models.BooleanField(default=True),
        ),
    ]
