# Generated by Django 4.1.6 on 2023-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_elevatormodel_moving'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatormodel',
            name='elevator_step',
            field=models.CharField(default='demand', max_length=200),
            preserve_default=False,
        ),
    ]
