# Generated by Django 4.1.6 on 2023-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_elevatormodel_elevator_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatormodel',
            name='elevator_step',
        ),
        migrations.AddField(
            model_name='elevatormodel',
            name='elevatorStep',
            field=models.CharField(choices=[('1', 'on demand'), ('2', 'moving'), ('3', 'resting')], default='1', max_length=200),
            preserve_default=False,
        ),
    ]
