# Generated by Django 4.1.6 on 2023-02-08 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_remove_elevatormodel_elevator_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatormodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevatormodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
